spring :
  datasource :
    driverClassName : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/BelajarTesting
    username : rizki
    password : mufrizal

  jpa :
    hibernate :
      ddl-auto : update

server :
  port : 8888
  context-path : /BelajarTesting